using System;
using System.Collections.Generic;

namespace EFCoreDemo_DbFirst.Models
{
    public partial class EmployeeApplication
    {
        public int EmployeeApplicationId { get; set; }
        public string HonorificMyanmar { get; set; }
        public string HonorificEnglish { get; set; }
        public string EmployeeNameMyanmar { get; set; }
        public string EmployeeNameEnglish { get; set; }
        public byte? EmployeeGender { get; set; }
        public string EmployeeDobDay { get; set; }
        public string EmployeeDobMonth { get; set; }
        public string EmployeeDobYear { get; set; }
        public string EmployeeNrcSr { get; set; }
        public string EmployeeNrcTownship { get; set; }
        public string EmployeeNrcType { get; set; }
        public string EmployeeNrcNo { get; set; }
        public string EmployeePassport { get; set; }
        public int? EmployeeNationalityId { get; set; }
        public string EmployeeFatherName { get; set; }
        public string EmployeeMotherName { get; set; }
        public string EmployeeAddressNumber { get; set; }
        public string EmployeeStreet { get; set; }
        public string EmployeeWard { get; set; }
        public string EmployeeTownship { get; set; }
        public string EmployeeRegion { get; set; }
        public string PermanentAddressNumber { get; set; }
        public string PermanentStreet { get; set; }
        public string PermanentWard { get; set; }
        public string PermanentTownship { get; set; }
        public string PermanentRegion { get; set; }
        public string EmployeePhone { get; set; }
        public string EmployeeFax { get; set; }
        public string EmployeeEmail { get; set; }
        public string Ssn { get; set; }
        public DateTime? ApplicationDate { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public byte? MaritalStatusType { get; set; }
        public string SpouseHonorificMyanmar { get; set; }
        public string SpouseName { get; set; }
        public string SpouseDobDay { get; set; }
        public string SpouseDobMonth { get; set; }
        public string SpouseDobYear { get; set; }
        public string Child1Name { get; set; }
        public byte? Child1Gender { get; set; }
        public string Child1DobDay { get; set; }
        public string Child1DobMonth { get; set; }
        public string Child1DobYear { get; set; }
        public string Child2Name { get; set; }
        public byte? Child2Gender { get; set; }
        public string Child2DobDay { get; set; }
        public string Child2DobMonth { get; set; }
        public string Child2DobYear { get; set; }
        public string Child3Name { get; set; }
        public byte? Child3Gender { get; set; }
        public string Child3DobDay { get; set; }
        public string Child3DobMonth { get; set; }
        public string Child3DobYear { get; set; }
        public string Child4Name { get; set; }
        public byte? Child4Gender { get; set; }
        public string Child4DobDay { get; set; }
        public string Child4DobMonth { get; set; }
        public string Child4DobYear { get; set; }
        public string Child5Name { get; set; }
        public byte? Child5Gender { get; set; }
        public string Child5DobDay { get; set; }
        public string Child5DobMonth { get; set; }
        public string Child5DobYear { get; set; }
        public string Child6Name { get; set; }
        public byte? Child6Gender { get; set; }
        public string Child6DobDay { get; set; }
        public string Child6DobMonth { get; set; }
        public string Child6DobYear { get; set; }
        public string Child7Name { get; set; }
        public byte? Child7Gender { get; set; }
        public string Child7DobDay { get; set; }
        public string Child7DobMonth { get; set; }
        public string Child7DobYear { get; set; }
        public string Child8Name { get; set; }
        public byte? Child8Gender { get; set; }
        public string Child8DobDay { get; set; }
        public string Child8DobMonth { get; set; }
        public string Child8DobYear { get; set; }
        public string Child9Name { get; set; }
        public byte? Child9Gender { get; set; }
        public string Child9DobDay { get; set; }
        public string Child9DobMonth { get; set; }
        public string Child9DobYear { get; set; }
        public string Child10Name { get; set; }
        public byte? Child10Gender { get; set; }
        public string Child10DobDay { get; set; }
        public string Child10DobMonth { get; set; }
        public string Child10DobYear { get; set; }
        public string Nominee1HonorificMyanmar { get; set; }
        public string Nominee1Name { get; set; }
        public string Nominee1Gender { get; set; }
        public string Nominee1DobDay { get; set; }
        public string Nominee1DobMonth { get; set; }
        public string Nominee1DobYear { get; set; }
        public string Nominee1Relationship { get; set; }
        public string Nominee2HonorificMyanmar { get; set; }
        public string Nominee2Name { get; set; }
        public string Nominee2Gender { get; set; }
        public string Nominee2DobDay { get; set; }
        public string Nominee2DobMonth { get; set; }
        public string Nominee2DobYear { get; set; }
        public string Nominee2Relationship { get; set; }
        public string Nominee3HonorificMyanmar { get; set; }
        public string Nominee3Name { get; set; }
        public string Nominee3Gender { get; set; }
        public string Nominee3DobDay { get; set; }
        public string Nominee3DobMonth { get; set; }
        public string Nominee3DobYear { get; set; }
        public string Nominee3Relationship { get; set; }
        public string Nominee4HonorificMyanmar { get; set; }
        public string Nominee4Name { get; set; }
        public string Nominee4Gender { get; set; }
        public string Nominee4DobDay { get; set; }
        public string Nominee4DobMonth { get; set; }
        public string Nominee4DobYear { get; set; }
        public string Nominee4Relationship { get; set; }
        public string Nominee5HonorificMyanmar { get; set; }
        public string Nominee5Name { get; set; }
        public string Nominee5Gender { get; set; }
        public string Nominee5DobDay { get; set; }
        public string Nominee5DobMonth { get; set; }
        public string Nominee5DobYear { get; set; }
        public string Nominee5Relationship { get; set; }
        public string Nominee6HonorificMyanmar { get; set; }
        public string Nominee6Name { get; set; }
        public string Nominee6Gender { get; set; }
        public string Nominee6DobDay { get; set; }
        public string Nominee6DobMonth { get; set; }
        public string Nominee6DobYear { get; set; }
        public string Nominee6Relationship { get; set; }
        public string Nominee7HonorificMyanmar { get; set; }
        public string Nominee7Name { get; set; }
        public string Nominee7Gender { get; set; }
        public string Nominee7DobDay { get; set; }
        public string Nominee7DobMonth { get; set; }
        public string Nominee7DobYear { get; set; }
        public string Nominee7Relationship { get; set; }
        public string Nominee8HonorificMyanmar { get; set; }
        public string Nominee8Name { get; set; }
        public string Nominee8Gender { get; set; }
        public string Nominee8DobDay { get; set; }
        public string Nominee8DobMonth { get; set; }
        public string Nominee8DobYear { get; set; }
        public string Nominee8Relationship { get; set; }
        public string Nominee9HonorificMyanmar { get; set; }
        public string Nominee9Name { get; set; }
        public string Nominee9Gender { get; set; }
        public string Nominee9DobDay { get; set; }
        public string Nominee9DobMonth { get; set; }
        public string Nominee9DobYear { get; set; }
        public string Nominee9Relationship { get; set; }
        public string Nominee10HonorificMyanmar { get; set; }
        public string Nominee10Name { get; set; }
        public string Nominee10Gender { get; set; }
        public string Nominee10DobDay { get; set; }
        public string Nominee10DobMonth { get; set; }
        public string Nominee10DobYear { get; set; }
        public string Nominee10Relationship { get; set; }
        public string EmployeeDesignationL1 { get; set; }
        public string EmployeeDesignationL2 { get; set; }
        public string EmployeeDesignationL3 { get; set; }
        public string EmployeeDesignationCode { get; set; }
        public string OtherDesignation { get; set; }
        public string IncomeType { get; set; }
        public string EstablishmentName { get; set; }
        public string EstablishmentNo { get; set; }
        public string JoinedDay { get; set; }
        public string JoinedMonth { get; set; }
        public string JoinedYear { get; set; }
        public decimal? Salary { get; set; }
        public string Currency { get; set; }
        public int? EffectiveDay { get; set; }
        public int? EffectiveMonth { get; set; }
        public int? EffectiveYear { get; set; }
        public int? UserId { get; set; }
        public bool? EmployeeState { get; set; }
        public bool? OfficerState { get; set; }
        public string SsbOfficeCode { get; set; }
        public string SsbTownshipCode { get; set; }
        public string SsbRegionCode { get; set; }
        public string OfficerDecision { get; set; }
        public string OfficerRemark { get; set; }
        public int? AmendmentTypeId { get; set; }
        public string AmendmentTypeName { get; set; }
        public DateTime? AmendmentTypeDate { get; set; }
        public string AmendmentTypeRemark { get; set; }
        public string AmendmentTypeRemark2 { get; set; }
        public DateTime? LeaveDate { get; set; }
        public string LeaveRemark { get; set; }
    }
}
